# Generated by Django 5.2.9 on 2025-12-03 21:28

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="call_to_action",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="homepage",
            name="faq",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="testimonial_slider",
            field=wagtail.fields.StreamField(
                [("testimonial", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.TextBlock", (), {"required": True}),
                    1: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 0), ("author", 1), ("photo", 2)]],
                        {},
                    ),
                },
            ),
        ),
    ]
